/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "LMSQUEEZY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LOGTO_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LOGTO_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LOGTO_M2M_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LOGTO_M2M_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXTAUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXTAUTH_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_PUBLIC_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "mikandev-payments": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
